// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop__Syms.h"
#include "Vtop_lab2_proc_ProcAlt.h"

VL_ATTR_COLD void Vtop_lab2_proc_ProcAlt___ctor_var_reset(Vtop_lab2_proc_ProcAlt* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+        Vtop_lab2_proc_ProcAlt___ctor_var_reset\n"); );
    // Body
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reset = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__imem_reqstream_msg);
    vlSelf->__PVT__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__dmem_reqstream_msg);
    vlSelf->__PVT__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__core_id = VL_RAND_RESET_I(32);
    vlSelf->__PVT__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_queue_num_free_entries = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(77, vlSelf->__PVT__imem_reqstream_enq_msg);
    vlSelf->__PVT__imem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(77, vlSelf->__Vcellout__imem_queue__deq_msg);
    VL_RAND_RESET_W(77, vlSelf->__Vcellinp__imem_queue__enq_msg);
    vlSelf->__PVT__imem_respstream_drop = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_drop_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__imem_respstream_drop_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_drop_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vcellout__imem_respstream_drop_unit__ostream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vcellinp__imem_respstream_drop_unit__istream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__dmem_queue_num_free_entries = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__dmem_reqstream_enq_msg);
    vlSelf->__PVT__dmem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__dmem_reqstream_enq_msg_data = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(77, vlSelf->__Vcellout__dmem_queue__deq_msg);
    VL_RAND_RESET_W(77, vlSelf->__Vcellinp__dmem_queue__enq_msg);
    vlSelf->__PVT__proc2mngr_queue_num_free_entries = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_enq_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__proc2mngr_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reg_en_F = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pc_sel_F = VL_RAND_RESET_I(2);
    vlSelf->__PVT__reg_en_D = VL_RAND_RESET_I(1);
    vlSelf->__PVT__op1_sel_D = VL_RAND_RESET_I(1);
    vlSelf->__PVT__op2_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__PVT__csrr_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__PVT__imm_type_D = VL_RAND_RESET_I(3);
    vlSelf->__PVT__op1_byp_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__PVT__op2_byp_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__PVT__reg_en_X = VL_RAND_RESET_I(1);
    vlSelf->__PVT__alu_fn_X = VL_RAND_RESET_I(4);
    vlSelf->__PVT__ex_result_sel_X = VL_RAND_RESET_I(2);
    vlSelf->__PVT__dmem_reqstream_type_X = VL_RAND_RESET_I(2);
    vlSelf->__PVT__imul_req_val_D = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imul_resp_val_X = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imul_req_rdy_D = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imul_resp_rdy_X = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reg_en_M = VL_RAND_RESET_I(1);
    vlSelf->__PVT__wb_result_sel_M = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reg_en_W = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rf_waddr_W = VL_RAND_RESET_I(5);
    vlSelf->__PVT__rf_wen_W = VL_RAND_RESET_I(1);
    vlSelf->__PVT__stats_en_wen_W = VL_RAND_RESET_I(1);
    vlSelf->__PVT__inst_D = VL_RAND_RESET_I(32);
    vlSelf->__PVT__br_cond_eq_X = VL_RAND_RESET_I(1);
    vlSelf->__PVT__br_cond_lt_X = VL_RAND_RESET_I(1);
    vlSelf->__PVT__br_cond_ltu_X = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__dpath__dmem_respstream_msg_data = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__PVT__str);
    VL_RAND_RESET_W(4096, vlSelf->__PVT__temp);
    vlSelf->__PVT__idx1 = VL_RAND_RESET_I(32);
    vlSelf->__PVT__idx0 = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__clk = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reset = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__imem_reqstream_msg);
    vlSelf->__Vtogcov__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__dmem_reqstream_msg);
    vlSelf->__Vtogcov__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__core_id = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_queue_num_free_entries = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__imem_reqstream_enq_msg);
    vlSelf->__Vtogcov__imem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__imem_respstream_drop = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_drop_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__imem_respstream_drop_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_drop_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_queue_num_free_entries = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__dmem_reqstream_enq_msg);
    vlSelf->__Vtogcov__dmem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__dmem_reqstream_enq_msg_data = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_queue_num_free_entries = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_enq_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reg_en_F = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__pc_sel_F = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__reg_en_D = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__op1_sel_D = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__op2_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__csrr_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__imm_type_D = VL_RAND_RESET_I(3);
    vlSelf->__Vtogcov__op1_byp_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__op2_byp_sel_D = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__reg_en_X = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__alu_fn_X = VL_RAND_RESET_I(4);
    vlSelf->__Vtogcov__ex_result_sel_X = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__dmem_reqstream_type_X = VL_RAND_RESET_I(2);
    vlSelf->__Vtogcov__imul_req_val_D = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imul_resp_val_X = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imul_req_rdy_D = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imul_resp_rdy_X = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reg_en_M = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__wb_result_sel_M = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reg_en_W = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__rf_waddr_W = VL_RAND_RESET_I(5);
    vlSelf->__Vtogcov__rf_wen_W = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__stats_en_wen_W = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__inst_D = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__br_cond_eq_X = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__br_cond_lt_X = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__br_cond_ltu_X = VL_RAND_RESET_I(1);
}
