// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_LAB2_PROC_PROCALTCTRL_H_
#define VERILATED_VTOP_LAB2_PROC_PROCALTCTRL_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
#include "verilated_timing.h"
class Vtop_lab2_proc_tinyrv2_encoding_InstUnpack;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_lab2_proc_ProcAltCtrl final : public VerilatedModule {
  public:
    // CELLS
    Vtop_lab2_proc_tinyrv2_encoding_InstUnpack* __PVT__inst_unpack;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__reset,0,0);
        VL_OUT8(__PVT__imem_reqstream_val,0,0);
        VL_IN8(__PVT__imem_reqstream_rdy,0,0);
        VL_IN8(__PVT__imem_respstream_val,0,0);
        VL_OUT8(__PVT__imem_respstream_rdy,0,0);
        VL_OUT8(__PVT__imem_respstream_drop,0,0);
        VL_OUT8(__PVT__dmem_reqstream_val,0,0);
        VL_IN8(__PVT__dmem_reqstream_rdy,0,0);
        VL_IN8(__PVT__dmem_respstream_val,0,0);
        VL_OUT8(__PVT__dmem_respstream_rdy,0,0);
        VL_IN8(__PVT__mngr2proc_val,0,0);
        VL_OUT8(__PVT__mngr2proc_rdy,0,0);
        VL_OUT8(__PVT__proc2mngr_val,0,0);
        VL_IN8(__PVT__proc2mngr_rdy,0,0);
        VL_OUT8(__PVT__reg_en_F,0,0);
        VL_OUT8(__PVT__pc_sel_F,1,0);
        VL_OUT8(__PVT__reg_en_D,0,0);
        VL_OUT8(__PVT__op1_sel_D,0,0);
        VL_OUT8(__PVT__op2_sel_D,1,0);
        VL_OUT8(__PVT__csrr_sel_D,1,0);
        VL_OUT8(__PVT__imm_type_D,2,0);
        VL_OUT8(__PVT__reg_en_X,0,0);
        VL_OUT8(__PVT__alu_fn_X,3,0);
        VL_OUT8(__PVT__ex_result_sel_X,1,0);
        VL_OUT8(__PVT__dmem_reqstream_type_X,1,0);
        VL_OUT8(__PVT__op1_byp_sel_D,1,0);
        VL_OUT8(__PVT__op2_byp_sel_D,1,0);
        VL_OUT8(__PVT__imul_req_val_D,0,0);
        VL_OUT8(__PVT__imul_resp_rdy_X,0,0);
        VL_IN8(__PVT__imul_req_rdy_D,0,0);
        VL_IN8(__PVT__imul_resp_val_X,0,0);
        VL_OUT8(__PVT__reg_en_M,0,0);
        VL_OUT8(__PVT__wb_result_sel_M,0,0);
        VL_OUT8(__PVT__reg_en_W,0,0);
        VL_OUT8(__PVT__rf_waddr_W,4,0);
        VL_OUT8(__PVT__rf_wen_W,0,0);
        VL_OUT8(__PVT__stats_en_wen_W,0,0);
        VL_IN8(__PVT__br_cond_eq_X,0,0);
        VL_IN8(__PVT__br_cond_lt_X,0,0);
        VL_IN8(__PVT__br_cond_ltu_X,0,0);
        VL_OUT8(__PVT__commit_inst,0,0);
        CData/*0:0*/ __PVT__val_F;
        CData/*0:0*/ __PVT__val_D;
        CData/*0:0*/ __PVT__val_X;
        CData/*0:0*/ __PVT__val_M;
        CData/*0:0*/ __PVT__val_W;
        CData/*0:0*/ __PVT__ostall_F;
        CData/*0:0*/ __PVT__ostall_D;
        CData/*0:0*/ __PVT__ostall_X;
        CData/*0:0*/ __PVT__ostall_M;
        CData/*0:0*/ __PVT__ostall_W;
        CData/*0:0*/ __PVT__stall_F;
        CData/*0:0*/ __PVT__stall_D;
        CData/*0:0*/ __PVT__stall_X;
        CData/*0:0*/ __PVT__stall_M;
        CData/*0:0*/ __PVT__stall_W;
        CData/*0:0*/ __PVT__osquash_D;
        CData/*0:0*/ __PVT__osquash_X;
        CData/*0:0*/ __PVT__squash_F;
        CData/*0:0*/ __PVT__squash_D;
        CData/*0:0*/ __PVT__pc_redirect_D;
        CData/*0:0*/ __PVT__pc_redirect_X;
        CData/*1:0*/ __PVT__pc_sel_D;
    };
    struct {
        CData/*1:0*/ __PVT__pc_sel_X;
        CData/*0:0*/ __PVT__next_val_F;
        CData/*4:0*/ __PVT__inst_rd_D;
        CData/*4:0*/ __PVT__inst_rs1_D;
        CData/*4:0*/ __PVT__inst_rs2_D;
        CData/*0:0*/ __PVT__inst_val_D;
        CData/*2:0*/ __PVT__br_type_D;
        CData/*0:0*/ __PVT__rs1_en_D;
        CData/*0:0*/ __PVT__rs2_en_D;
        CData/*3:0*/ __PVT__alu_fn_D;
        CData/*1:0*/ __PVT__dmem_reqstream_type_D;
        CData/*0:0*/ __PVT__wb_result_sel_D;
        CData/*0:0*/ __PVT__rf_wen_D;
        CData/*0:0*/ __PVT__csrr_D;
        CData/*0:0*/ __PVT__csrw_D;
        CData/*0:0*/ __PVT__proc2mngr_val_D;
        CData/*0:0*/ __PVT__mngr2proc_rdy_D;
        CData/*0:0*/ __PVT__stats_en_wen_D;
        CData/*4:0*/ __PVT__rf_waddr_D;
        CData/*0:0*/ __PVT__ostall_mngr2proc_D;
        CData/*0:0*/ __PVT__ostall_waddr_X_rs1_D;
        CData/*0:0*/ __PVT__ostall_waddr_M_rs1_D;
        CData/*0:0*/ __PVT__ostall_waddr_X_rs2_D;
        CData/*0:0*/ __PVT__ostall_waddr_M_rs2_D;
        CData/*0:0*/ __PVT__ostall_hazard_D;
        CData/*0:0*/ __PVT__bypass_waddr_X_rs1_D;
        CData/*0:0*/ __PVT__bypass_waddr_X_rs2_D;
        CData/*0:0*/ __PVT__bypass_waddr_M_rs1_D;
        CData/*0:0*/ __PVT__bypass_waddr_M_rs2_D;
        CData/*0:0*/ __PVT__bypass_waddr_W_rs1_D;
        CData/*0:0*/ __PVT__bypass_waddr_W_rs2_D;
        CData/*0:0*/ __PVT__next_val_D;
        CData/*0:0*/ __PVT__wb_result_sel_X;
        CData/*0:0*/ __PVT__rf_wen_X;
        CData/*4:0*/ __PVT__rf_waddr_X;
        CData/*0:0*/ __PVT__proc2mngr_val_X;
        CData/*0:0*/ __PVT__stats_en_wen_X;
        CData/*2:0*/ __PVT__br_type_X;
        CData/*0:0*/ __PVT__next_val_X;
        CData/*1:0*/ __PVT__dmem_reqstream_type_M;
        CData/*0:0*/ __PVT__rf_wen_M;
        CData/*4:0*/ __PVT__rf_waddr_M;
        CData/*0:0*/ __PVT__proc2mngr_val_M;
        CData/*0:0*/ __PVT__stats_en_wen_M;
        CData/*0:0*/ __PVT__next_val_M;
        CData/*0:0*/ __PVT__proc2mngr_val_W;
        CData/*0:0*/ __PVT__rf_wen_pending_W;
        CData/*0:0*/ __PVT__stats_en_wen_pending_W;
        CData/*0:0*/ __Vtogcov__clk;
        CData/*0:0*/ __Vtogcov__reset;
        CData/*0:0*/ __Vtogcov__imem_reqstream_val;
        CData/*0:0*/ __Vtogcov__imem_reqstream_rdy;
        CData/*0:0*/ __Vtogcov__imem_respstream_val;
        CData/*0:0*/ __Vtogcov__imem_respstream_rdy;
        CData/*0:0*/ __Vtogcov__imem_respstream_drop;
        CData/*0:0*/ __Vtogcov__dmem_reqstream_val;
        CData/*0:0*/ __Vtogcov__dmem_reqstream_rdy;
        CData/*0:0*/ __Vtogcov__dmem_respstream_val;
        CData/*0:0*/ __Vtogcov__dmem_respstream_rdy;
        CData/*0:0*/ __Vtogcov__mngr2proc_val;
        CData/*0:0*/ __Vtogcov__mngr2proc_rdy;
        CData/*0:0*/ __Vtogcov__proc2mngr_val;
        CData/*0:0*/ __Vtogcov__proc2mngr_rdy;
        CData/*0:0*/ __Vtogcov__reg_en_F;
    };
    struct {
        CData/*1:0*/ __Vtogcov__pc_sel_F;
        CData/*0:0*/ __Vtogcov__reg_en_D;
        CData/*0:0*/ __Vtogcov__op1_sel_D;
        CData/*1:0*/ __Vtogcov__op2_sel_D;
        CData/*1:0*/ __Vtogcov__csrr_sel_D;
        CData/*2:0*/ __Vtogcov__imm_type_D;
        CData/*0:0*/ __Vtogcov__reg_en_X;
        CData/*3:0*/ __Vtogcov__alu_fn_X;
        CData/*1:0*/ __Vtogcov__ex_result_sel_X;
        CData/*1:0*/ __Vtogcov__dmem_reqstream_type_X;
        CData/*1:0*/ __Vtogcov__op1_byp_sel_D;
        CData/*1:0*/ __Vtogcov__op2_byp_sel_D;
        CData/*0:0*/ __Vtogcov__imul_req_val_D;
        CData/*0:0*/ __Vtogcov__imul_resp_rdy_X;
        CData/*0:0*/ __Vtogcov__imul_req_rdy_D;
        CData/*0:0*/ __Vtogcov__imul_resp_val_X;
        CData/*0:0*/ __Vtogcov__reg_en_M;
        CData/*0:0*/ __Vtogcov__wb_result_sel_M;
        CData/*0:0*/ __Vtogcov__reg_en_W;
        CData/*4:0*/ __Vtogcov__rf_waddr_W;
        CData/*0:0*/ __Vtogcov__rf_wen_W;
        CData/*0:0*/ __Vtogcov__stats_en_wen_W;
        CData/*0:0*/ __Vtogcov__br_cond_eq_X;
        CData/*0:0*/ __Vtogcov__br_cond_lt_X;
        CData/*0:0*/ __Vtogcov__br_cond_ltu_X;
        CData/*0:0*/ __Vtogcov__commit_inst;
        CData/*0:0*/ __Vtogcov__val_F;
        CData/*0:0*/ __Vtogcov__val_D;
        CData/*0:0*/ __Vtogcov__val_X;
        CData/*0:0*/ __Vtogcov__val_M;
        CData/*0:0*/ __Vtogcov__val_W;
        CData/*0:0*/ __Vtogcov__ostall_F;
        CData/*0:0*/ __Vtogcov__ostall_D;
        CData/*0:0*/ __Vtogcov__ostall_X;
        CData/*0:0*/ __Vtogcov__ostall_M;
        CData/*0:0*/ __Vtogcov__ostall_W;
        CData/*0:0*/ __Vtogcov__stall_F;
        CData/*0:0*/ __Vtogcov__stall_D;
        CData/*0:0*/ __Vtogcov__stall_X;
        CData/*0:0*/ __Vtogcov__stall_M;
        CData/*0:0*/ __Vtogcov__stall_W;
        CData/*0:0*/ __Vtogcov__osquash_D;
        CData/*0:0*/ __Vtogcov__osquash_X;
        CData/*0:0*/ __Vtogcov__squash_F;
        CData/*0:0*/ __Vtogcov__squash_D;
        CData/*0:0*/ __Vtogcov__pc_redirect_D;
        CData/*0:0*/ __Vtogcov__pc_redirect_X;
        CData/*1:0*/ __Vtogcov__pc_sel_D;
        CData/*1:0*/ __Vtogcov__pc_sel_X;
        CData/*0:0*/ __Vtogcov__next_val_F;
        CData/*4:0*/ __Vtogcov__inst_rd_D;
        CData/*4:0*/ __Vtogcov__inst_rs1_D;
        CData/*4:0*/ __Vtogcov__inst_rs2_D;
        CData/*0:0*/ __Vtogcov__inst_val_D;
        CData/*2:0*/ __Vtogcov__br_type_D;
        CData/*0:0*/ __Vtogcov__rs1_en_D;
        CData/*0:0*/ __Vtogcov__rs2_en_D;
        CData/*3:0*/ __Vtogcov__alu_fn_D;
        CData/*1:0*/ __Vtogcov__dmem_reqstream_type_D;
        CData/*0:0*/ __Vtogcov__wb_result_sel_D;
        CData/*0:0*/ __Vtogcov__rf_wen_D;
        CData/*0:0*/ __Vtogcov__csrr_D;
        CData/*0:0*/ __Vtogcov__csrw_D;
        CData/*0:0*/ __Vtogcov__proc2mngr_val_D;
    };
    struct {
        CData/*0:0*/ __Vtogcov__mngr2proc_rdy_D;
        CData/*0:0*/ __Vtogcov__stats_en_wen_D;
        CData/*4:0*/ __Vtogcov__rf_waddr_D;
        CData/*0:0*/ __Vtogcov__ostall_mngr2proc_D;
        CData/*0:0*/ __Vtogcov__ostall_waddr_X_rs1_D;
        CData/*0:0*/ __Vtogcov__ostall_waddr_M_rs1_D;
        CData/*0:0*/ __Vtogcov__ostall_waddr_X_rs2_D;
        CData/*0:0*/ __Vtogcov__ostall_waddr_M_rs2_D;
        CData/*0:0*/ __Vtogcov__ostall_hazard_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_X_rs1_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_X_rs2_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_M_rs1_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_M_rs2_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_W_rs1_D;
        CData/*0:0*/ __Vtogcov__bypass_waddr_W_rs2_D;
        CData/*0:0*/ __Vtogcov__next_val_D;
        CData/*0:0*/ __Vtogcov__wb_result_sel_X;
        CData/*0:0*/ __Vtogcov__rf_wen_X;
        CData/*4:0*/ __Vtogcov__rf_waddr_X;
        CData/*0:0*/ __Vtogcov__proc2mngr_val_X;
        CData/*0:0*/ __Vtogcov__stats_en_wen_X;
        CData/*2:0*/ __Vtogcov__br_type_X;
        CData/*0:0*/ __Vtogcov__next_val_X;
        CData/*1:0*/ __Vtogcov__dmem_reqstream_type_M;
        CData/*0:0*/ __Vtogcov__rf_wen_M;
        CData/*4:0*/ __Vtogcov__rf_waddr_M;
        CData/*0:0*/ __Vtogcov__proc2mngr_val_M;
        CData/*0:0*/ __Vtogcov__stats_en_wen_M;
        CData/*0:0*/ __Vtogcov__next_val_M;
        CData/*0:0*/ __Vtogcov__proc2mngr_val_W;
        CData/*0:0*/ __Vtogcov__rf_wen_pending_W;
        CData/*0:0*/ __Vtogcov__stats_en_wen_pending_W;
        CData/*0:0*/ __Vtask_cs__0__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__0__cs_br_type;
        CData/*2:0*/ __Vtask_cs__0__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__0__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__0__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__0__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__0__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__0__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__0__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__0__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__0__cs_csrr;
        CData/*0:0*/ __Vtask_cs__0__cs_csrw;
        CData/*0:0*/ __Vtask_cs__1__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__1__cs_br_type;
        CData/*2:0*/ __Vtask_cs__1__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__1__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__1__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__1__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__1__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__1__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__1__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__1__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__1__cs_csrr;
        CData/*0:0*/ __Vtask_cs__1__cs_csrw;
        CData/*0:0*/ __Vtask_cs__2__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__2__cs_br_type;
        CData/*2:0*/ __Vtask_cs__2__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__2__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__2__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__2__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__2__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__2__cs_dmem_reqstream_type;
    };
    struct {
        CData/*0:0*/ __Vtask_cs__2__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__2__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__2__cs_csrr;
        CData/*0:0*/ __Vtask_cs__2__cs_csrw;
        CData/*0:0*/ __Vtask_cs__3__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__3__cs_br_type;
        CData/*2:0*/ __Vtask_cs__3__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__3__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__3__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__3__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__3__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__3__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__3__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__3__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__3__cs_csrr;
        CData/*0:0*/ __Vtask_cs__3__cs_csrw;
        CData/*0:0*/ __Vtask_cs__4__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__4__cs_br_type;
        CData/*2:0*/ __Vtask_cs__4__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__4__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__4__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__4__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__4__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__4__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__4__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__4__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__4__cs_csrr;
        CData/*0:0*/ __Vtask_cs__4__cs_csrw;
        CData/*0:0*/ __Vtask_cs__5__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__5__cs_br_type;
        CData/*2:0*/ __Vtask_cs__5__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__5__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__5__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__5__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__5__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__5__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__5__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__5__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__5__cs_csrr;
        CData/*0:0*/ __Vtask_cs__5__cs_csrw;
        CData/*0:0*/ __Vtask_cs__6__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__6__cs_br_type;
        CData/*2:0*/ __Vtask_cs__6__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__6__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__6__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__6__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__6__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__6__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__6__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__6__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__6__cs_csrr;
        CData/*0:0*/ __Vtask_cs__6__cs_csrw;
        CData/*0:0*/ __Vtask_cs__7__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__7__cs_br_type;
        CData/*2:0*/ __Vtask_cs__7__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__7__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__7__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__7__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__7__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__7__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__7__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__7__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__7__cs_csrr;
        CData/*0:0*/ __Vtask_cs__7__cs_csrw;
    };
    struct {
        CData/*0:0*/ __Vtask_cs__8__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__8__cs_br_type;
        CData/*2:0*/ __Vtask_cs__8__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__8__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__8__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__8__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__8__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__8__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__8__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__8__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__8__cs_csrr;
        CData/*0:0*/ __Vtask_cs__8__cs_csrw;
        CData/*0:0*/ __Vtask_cs__9__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__9__cs_br_type;
        CData/*2:0*/ __Vtask_cs__9__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__9__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__9__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__9__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__9__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__9__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__9__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__9__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__9__cs_csrr;
        CData/*0:0*/ __Vtask_cs__9__cs_csrw;
        CData/*0:0*/ __Vtask_cs__10__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__10__cs_br_type;
        CData/*2:0*/ __Vtask_cs__10__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__10__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__10__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__10__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__10__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__10__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__10__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__10__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__10__cs_csrr;
        CData/*0:0*/ __Vtask_cs__10__cs_csrw;
        CData/*0:0*/ __Vtask_cs__11__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__11__cs_br_type;
        CData/*2:0*/ __Vtask_cs__11__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__11__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__11__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__11__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__11__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__11__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__11__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__11__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__11__cs_csrr;
        CData/*0:0*/ __Vtask_cs__11__cs_csrw;
        CData/*0:0*/ __Vtask_cs__12__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__12__cs_br_type;
        CData/*2:0*/ __Vtask_cs__12__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__12__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__12__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__12__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__12__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__12__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__12__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__12__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__12__cs_csrr;
        CData/*0:0*/ __Vtask_cs__12__cs_csrw;
        CData/*0:0*/ __Vtask_cs__13__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__13__cs_br_type;
        CData/*2:0*/ __Vtask_cs__13__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__13__cs_rs1_en;
    };
    struct {
        CData/*1:0*/ __Vtask_cs__13__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__13__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__13__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__13__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__13__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__13__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__13__cs_csrr;
        CData/*0:0*/ __Vtask_cs__13__cs_csrw;
        CData/*0:0*/ __Vtask_cs__14__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__14__cs_br_type;
        CData/*2:0*/ __Vtask_cs__14__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__14__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__14__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__14__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__14__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__14__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__14__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__14__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__14__cs_csrr;
        CData/*0:0*/ __Vtask_cs__14__cs_csrw;
        CData/*0:0*/ __Vtask_cs__15__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__15__cs_br_type;
        CData/*2:0*/ __Vtask_cs__15__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__15__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__15__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__15__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__15__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__15__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__15__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__15__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__15__cs_csrr;
        CData/*0:0*/ __Vtask_cs__15__cs_csrw;
        CData/*0:0*/ __Vtask_cs__16__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__16__cs_br_type;
        CData/*2:0*/ __Vtask_cs__16__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__16__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__16__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__16__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__16__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__16__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__16__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__16__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__16__cs_csrr;
        CData/*0:0*/ __Vtask_cs__16__cs_csrw;
        CData/*0:0*/ __Vtask_cs__17__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__17__cs_br_type;
        CData/*2:0*/ __Vtask_cs__17__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__17__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__17__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__17__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__17__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__17__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__17__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__17__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__17__cs_csrr;
        CData/*0:0*/ __Vtask_cs__17__cs_csrw;
        CData/*0:0*/ __Vtask_cs__18__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__18__cs_br_type;
        CData/*2:0*/ __Vtask_cs__18__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__18__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__18__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__18__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__18__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__18__cs_dmem_reqstream_type;
    };
    struct {
        CData/*0:0*/ __Vtask_cs__18__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__18__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__18__cs_csrr;
        CData/*0:0*/ __Vtask_cs__18__cs_csrw;
        CData/*0:0*/ __Vtask_cs__19__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__19__cs_br_type;
        CData/*2:0*/ __Vtask_cs__19__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__19__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__19__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__19__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__19__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__19__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__19__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__19__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__19__cs_csrr;
        CData/*0:0*/ __Vtask_cs__19__cs_csrw;
        CData/*0:0*/ __Vtask_cs__20__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__20__cs_br_type;
        CData/*2:0*/ __Vtask_cs__20__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__20__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__20__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__20__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__20__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__20__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__20__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__20__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__20__cs_csrr;
        CData/*0:0*/ __Vtask_cs__20__cs_csrw;
        CData/*0:0*/ __Vtask_cs__21__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__21__cs_br_type;
        CData/*2:0*/ __Vtask_cs__21__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__21__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__21__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__21__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__21__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__21__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__21__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__21__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__21__cs_csrr;
        CData/*0:0*/ __Vtask_cs__21__cs_csrw;
        CData/*0:0*/ __Vtask_cs__22__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__22__cs_br_type;
        CData/*2:0*/ __Vtask_cs__22__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__22__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__22__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__22__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__22__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__22__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__22__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__22__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__22__cs_csrr;
        CData/*0:0*/ __Vtask_cs__22__cs_csrw;
        CData/*0:0*/ __Vtask_cs__23__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__23__cs_br_type;
        CData/*2:0*/ __Vtask_cs__23__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__23__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__23__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__23__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__23__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__23__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__23__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__23__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__23__cs_csrr;
        CData/*0:0*/ __Vtask_cs__23__cs_csrw;
    };
    struct {
        CData/*0:0*/ __Vtask_cs__24__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__24__cs_br_type;
        CData/*2:0*/ __Vtask_cs__24__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__24__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__24__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__24__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__24__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__24__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__24__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__24__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__24__cs_csrr;
        CData/*0:0*/ __Vtask_cs__24__cs_csrw;
        CData/*0:0*/ __Vtask_cs__25__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__25__cs_br_type;
        CData/*2:0*/ __Vtask_cs__25__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__25__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__25__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__25__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__25__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__25__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__25__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__25__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__25__cs_csrr;
        CData/*0:0*/ __Vtask_cs__25__cs_csrw;
        CData/*0:0*/ __Vtask_cs__26__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__26__cs_br_type;
        CData/*2:0*/ __Vtask_cs__26__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__26__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__26__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__26__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__26__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__26__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__26__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__26__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__26__cs_csrr;
        CData/*0:0*/ __Vtask_cs__26__cs_csrw;
        CData/*0:0*/ __Vtask_cs__27__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__27__cs_br_type;
        CData/*2:0*/ __Vtask_cs__27__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__27__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__27__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__27__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__27__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__27__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__27__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__27__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__27__cs_csrr;
        CData/*0:0*/ __Vtask_cs__27__cs_csrw;
        CData/*0:0*/ __Vtask_cs__28__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__28__cs_br_type;
        CData/*2:0*/ __Vtask_cs__28__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__28__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__28__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__28__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__28__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__28__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__28__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__28__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__28__cs_csrr;
        CData/*0:0*/ __Vtask_cs__28__cs_csrw;
        CData/*0:0*/ __Vtask_cs__29__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__29__cs_br_type;
        CData/*2:0*/ __Vtask_cs__29__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__29__cs_rs1_en;
    };
    struct {
        CData/*1:0*/ __Vtask_cs__29__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__29__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__29__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__29__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__29__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__29__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__29__cs_csrr;
        CData/*0:0*/ __Vtask_cs__29__cs_csrw;
        CData/*0:0*/ __Vtask_cs__30__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__30__cs_br_type;
        CData/*2:0*/ __Vtask_cs__30__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__30__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__30__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__30__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__30__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__30__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__30__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__30__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__30__cs_csrr;
        CData/*0:0*/ __Vtask_cs__30__cs_csrw;
        CData/*0:0*/ __Vtask_cs__31__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__31__cs_br_type;
        CData/*2:0*/ __Vtask_cs__31__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__31__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__31__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__31__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__31__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__31__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__31__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__31__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__31__cs_csrr;
        CData/*0:0*/ __Vtask_cs__31__cs_csrw;
        CData/*0:0*/ __Vtask_cs__32__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__32__cs_br_type;
        CData/*2:0*/ __Vtask_cs__32__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__32__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__32__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__32__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__32__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__32__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__32__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__32__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__32__cs_csrr;
        CData/*0:0*/ __Vtask_cs__32__cs_csrw;
        CData/*0:0*/ __Vtask_cs__33__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__33__cs_br_type;
        CData/*2:0*/ __Vtask_cs__33__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__33__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__33__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__33__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__33__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__33__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__33__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__33__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__33__cs_csrr;
        CData/*0:0*/ __Vtask_cs__33__cs_csrw;
        CData/*0:0*/ __Vtask_cs__34__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__34__cs_br_type;
        CData/*2:0*/ __Vtask_cs__34__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__34__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__34__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__34__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__34__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__34__cs_dmem_reqstream_type;
    };
    struct {
        CData/*0:0*/ __Vtask_cs__34__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__34__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__34__cs_csrr;
        CData/*0:0*/ __Vtask_cs__34__cs_csrw;
        CData/*0:0*/ __Vtask_cs__35__cs_inst_val;
        CData/*2:0*/ __Vtask_cs__35__cs_br_type;
        CData/*2:0*/ __Vtask_cs__35__cs_imm_type;
        CData/*0:0*/ __Vtask_cs__35__cs_rs1_en;
        CData/*1:0*/ __Vtask_cs__35__cs_op2_sel;
        CData/*0:0*/ __Vtask_cs__35__cs_rs2_en;
        CData/*3:0*/ __Vtask_cs__35__cs_alu_fn;
        CData/*1:0*/ __Vtask_cs__35__cs_dmem_reqstream_type;
        CData/*0:0*/ __Vtask_cs__35__cs_wb_result_sel;
        CData/*0:0*/ __Vtask_cs__35__cs_rf_wen;
        CData/*0:0*/ __Vtask_cs__35__cs_csrr;
        CData/*0:0*/ __Vtask_cs__35__cs_csrw;
        CData/*0:0*/ __Vdly__val_F;
        CData/*0:0*/ __Vdly__val_D;
        CData/*0:0*/ __Vdly__val_X;
        CData/*0:0*/ __Vdly__rf_wen_X;
        CData/*3:0*/ __Vdly__alu_fn_X;
        CData/*4:0*/ __Vdly__rf_waddr_X;
        CData/*0:0*/ __Vdly__proc2mngr_val_X;
        CData/*1:0*/ __Vdly__dmem_reqstream_type_X;
        CData/*0:0*/ __Vdly__wb_result_sel_X;
        CData/*0:0*/ __Vdly__stats_en_wen_X;
        CData/*2:0*/ __Vdly__br_type_X;
        CData/*0:0*/ __Vdly__val_M;
        CData/*0:0*/ __Vdly__rf_wen_M;
        CData/*4:0*/ __Vdly__rf_waddr_M;
        CData/*0:0*/ __Vdly__proc2mngr_val_M;
        CData/*1:0*/ __Vdly__dmem_reqstream_type_M;
        CData/*0:0*/ __Vdly__wb_result_sel_M;
        CData/*0:0*/ __Vdly__stats_en_wen_M;
        CData/*0:0*/ __Vdly__val_W;
        CData/*0:0*/ __Vdly__rf_wen_pending_W;
        CData/*4:0*/ __Vdly__rf_waddr_W;
        CData/*0:0*/ __Vdly__proc2mngr_val_W;
        CData/*0:0*/ __Vdly__stats_en_wen_pending_W;
        SData/*11:0*/ __PVT__inst_csr_D;
        SData/*11:0*/ __Vtogcov__inst_csr_D;
        VL_IN(__PVT__inst_D,31,0);
        IData/*31:0*/ __PVT__inst_X;
        IData/*31:0*/ __PVT__inst_M;
        IData/*31:0*/ __PVT__inst_W;
        IData/*31:0*/ __Vtogcov__inst_D;
        IData/*31:0*/ __Vtogcov__inst_X;
        IData/*31:0*/ __Vtogcov__inst_M;
        IData/*31:0*/ __Vtogcov__inst_W;
        IData/*31:0*/ __Vdly__inst_X;
        IData/*31:0*/ __Vdly__inst_M;
        IData/*31:0*/ __Vdly__inst_W;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop_lab2_proc_ProcAltCtrl(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_lab2_proc_ProcAltCtrl();
    VL_UNCOPYABLE(Vtop_lab2_proc_ProcAltCtrl);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(std::atomic<uint32_t>* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
