// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop__Syms.h"
#include "Vtop_top.h"

VL_ATTR_COLD void Vtop_top___ctor_var_reset(Vtop_top* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_top___ctor_var_reset\n"); );
    // Body
    vlSelf->clk = VL_RAND_RESET_I(1);
    vlSelf->linetrace = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reset = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__imem_reqstream_msg);
    vlSelf->__PVT__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__dmem_reqstream_msg);
    vlSelf->__PVT__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__core_id = VL_RAND_RESET_I(32);
    vlSelf->__PVT__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__src_done = VL_RAND_RESET_I(1);
    vlSelf->__PVT__snk_done = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mem_clear = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 10; ++__Vi0) {
        vlSelf->__PVT__src_msgs[__Vi0] = VL_RAND_RESET_I(32);
    }
    for (int __Vi0 = 0; __Vi0 < 10; ++__Vi0) {
        vlSelf->__PVT__snk_msgs[__Vi0] = VL_RAND_RESET_I(32);
    }
    vlSelf->__Vcellout__mem__memresp1_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vcellout__mem__memresp0_msg = VL_RAND_RESET_Q(47);
    VL_RAND_RESET_W(77, vlSelf->__Vcellinp__mem__memreq1_msg);
    VL_RAND_RESET_W(77, vlSelf->__Vcellinp__mem__memreq0_msg);
    vlSelf->__PVT__idx = VL_RAND_RESET_I(32);
    vlSelf->__PVT__fp = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__clk = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__linetrace = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reset = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__imem_reqstream_msg);
    vlSelf->__Vtogcov__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__dmem_reqstream_msg);
    vlSelf->__Vtogcov__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__core_id = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__src_done = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__snk_done = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mem_clear = VL_RAND_RESET_I(1);
    vlSelf->__PVT__unnamedblk1__DOT__i = VL_RAND_RESET_I(32);
    vlSelf->__Vtask_load__0__filein = VL_RAND_RESET_I(32);
    vlSelf->__Vtask_load__1__file_load = 0;
    vlSelf->__Vtask_load__2__file_load = VL_RAND_RESET_I(32);
    vlSelf->__Vtask_load__3__file_load = 0;
    vlSelf->__Vtask_load__4__file_load = VL_RAND_RESET_I(32);
    vlSelf->__Vtask_load__5__file_load = 0;
    vlSelf->__Vtask_dump__6__filein = VL_RAND_RESET_I(32);
    vlSelf->__Vtask_dump__7__file_out = VL_RAND_RESET_I(32);
    VL_ZERO_RESET_W(4096, vlSelf->__Vtask_line_trace__11__trace_str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_val_rdy_str__12__trace);
    vlSelf->__Vtask_append_val_rdy_str__12__val = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_append_val_rdy_str__12__rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_val_rdy_str__12__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__13__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__13__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__14__trace);
    vlSelf->__Vtask_append_chars__14__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__14__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__15__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__15__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__16__trace);
    vlSelf->__Vtask_append_chars__16__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__16__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__17__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__17__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__18__trace);
    vlSelf->__Vtask_append_chars__18__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__18__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__19__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__19__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__20__trace);
    vlSelf->__Vtask_append_chars__20__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__20__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__21__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__21__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__22__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__22__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__23__trace);
    vlSelf->__Vtask_append_chars__23__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__23__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__24__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__24__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__25__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__25__str);
    VL_RAND_RESET_W(200, vlSelf->__Vfunc_disasm__26__Vfuncout);
    vlSelf->__Vfunc_disasm__26__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__27__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__27__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__28__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__28__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__29__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__29__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__30__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__30__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__31__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__31__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__32__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__32__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__33__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__33__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__34__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__34__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__35__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__35__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__36__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__36__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__37__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__37__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__38__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__38__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_u_sh12__39__Vfuncout = VL_RAND_RESET_I(20);
    vlSelf->__Vfunc_imm_u_sh12__39__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_u_sh12__40__Vfuncout = VL_RAND_RESET_I(20);
    vlSelf->__Vfunc_imm_u_sh12__40__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__41__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__41__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_s__42__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_s__42__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_j__43__Vfuncout = VL_RAND_RESET_I(21);
    vlSelf->__Vfunc_imm_j__43__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__44__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__44__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__45__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__45__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__46__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__46__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__47__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__47__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__48__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__48__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__49__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__49__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__50__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__50__inst = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__51__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__51__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_val_rdy_str__52__trace);
    vlSelf->__Vtask_append_val_rdy_str__52__val = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_append_val_rdy_str__52__rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_val_rdy_str__52__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__53__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__53__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__54__trace);
    vlSelf->__Vtask_append_chars__54__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__54__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__55__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__55__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__56__trace);
    vlSelf->__Vtask_append_chars__56__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__56__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__57__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__57__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__58__trace);
    vlSelf->__Vtask_append_chars__58__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__58__num = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__59__trace);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_str__59__str);
    VL_RAND_RESET_W(4096, vlSelf->__Vtask_append_chars__60__trace);
    vlSelf->__Vtask_append_chars__60__char = VL_RAND_RESET_I(8);
    vlSelf->__Vtask_append_chars__60__num = VL_RAND_RESET_I(32);
}
