// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop__Syms.h"
#include "Vtop_lab2_proc_ProcFLMultiCycle.h"

VL_ATTR_COLD void Vtop_lab2_proc_ProcFLMultiCycle___ctor_var_reset(Vtop_lab2_proc_ProcFLMultiCycle* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+        Vtop_lab2_proc_ProcFLMultiCycle___ctor_var_reset\n"); );
    // Body
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reset = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__imem_reqstream_msg);
    vlSelf->__PVT__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__dmem_reqstream_msg);
    vlSelf->__PVT__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__PVT__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__core_id = VL_RAND_RESET_I(32);
    vlSelf->__PVT__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_queue_num_free_entries = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(77, vlSelf->__PVT__imem_reqstream_enq_msg);
    vlSelf->__PVT__imem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__imem_reqstream_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__dmem_queue_num_free_entries = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__PVT__dmem_reqstream_enq_msg);
    vlSelf->__PVT__dmem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dmem_reqstream_enq_msg_type = VL_RAND_RESET_I(3);
    vlSelf->__PVT__dmem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__dmem_reqstream_enq_msg_data = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(77, vlSelf->__Vcellout__dmem_queue__deq_msg);
    VL_RAND_RESET_W(77, vlSelf->__Vcellinp__dmem_queue__enq_msg);
    vlSelf->__PVT__proc2mngr_queue_num_free_entries = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_enq_msg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__proc2mngr_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__PVT__proc2mngr_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__opcode = VL_RAND_RESET_I(7);
    vlSelf->__PVT__rd = VL_RAND_RESET_I(5);
    vlSelf->__PVT__rs1 = VL_RAND_RESET_I(5);
    vlSelf->__PVT__rs2 = VL_RAND_RESET_I(5);
    vlSelf->__PVT__funct3 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__funct7 = VL_RAND_RESET_I(7);
    vlSelf->__PVT__csr = VL_RAND_RESET_I(12);
    vlSelf->__PVT__PC = VL_RAND_RESET_I(32);
    vlSelf->__PVT__PC_prev = VL_RAND_RESET_I(32);
    vlSelf->__PVT__n_PC = VL_RAND_RESET_I(32);
    vlSelf->__PVT__inst = VL_RAND_RESET_I(32);
    vlSelf->__PVT__n_inst = VL_RAND_RESET_I(32);
    vlSelf->__PVT__print_trace = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 32; ++__Vi0) {
        vlSelf->__PVT__rf[__Vi0] = VL_RAND_RESET_I(32);
    }
    for (int __Vi0 = 0; __Vi0 < 32; ++__Vi0) {
        vlSelf->__PVT__n_rf[__Vi0] = VL_RAND_RESET_I(32);
    }
    vlSelf->__PVT__state = 0;
    vlSelf->__PVT__n_state = 0;
    VL_RAND_RESET_W(4096, vlSelf->__PVT__temp);
    VL_RAND_RESET_W(4096, vlSelf->__PVT__str);
    vlSelf->__PVT__idx1 = VL_RAND_RESET_I(32);
    vlSelf->__PVT__idx0 = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__clk = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__reset = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__mngr2proc_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__mngr2proc_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__imem_reqstream_msg);
    vlSelf->__Vtogcov__imem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__imem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_respstream_rdy = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__dmem_reqstream_msg);
    vlSelf->__Vtogcov__dmem_reqstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_msg = VL_RAND_RESET_Q(47);
    vlSelf->__Vtogcov__dmem_respstream_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_respstream_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__core_id = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__commit_inst = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__stats_en = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_queue_num_free_entries = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__imem_reqstream_enq_msg);
    vlSelf->__Vtogcov__imem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__imem_reqstream_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__dmem_queue_num_free_entries = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(77, vlSelf->__Vtogcov__dmem_reqstream_enq_msg);
    vlSelf->__Vtogcov__dmem_reqstream_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__dmem_reqstream_enq_msg_type = VL_RAND_RESET_I(3);
    vlSelf->__Vtogcov__dmem_reqstream_enq_msg_addr = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__dmem_reqstream_enq_msg_data = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_queue_num_free_entries = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_enq_msg = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__proc2mngr_enq_val = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__proc2mngr_enq_rdy = VL_RAND_RESET_I(1);
    vlSelf->__Vtogcov__opcode = VL_RAND_RESET_I(7);
    vlSelf->__Vtogcov__rd = VL_RAND_RESET_I(5);
    vlSelf->__Vtogcov__rs1 = VL_RAND_RESET_I(5);
    vlSelf->__Vtogcov__rs2 = VL_RAND_RESET_I(5);
    vlSelf->__Vtogcov__funct3 = VL_RAND_RESET_I(3);
    vlSelf->__Vtogcov__funct7 = VL_RAND_RESET_I(7);
    vlSelf->__Vtogcov__csr = VL_RAND_RESET_I(12);
    vlSelf->__Vtogcov__PC = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__PC_prev = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__n_PC = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__n_inst = VL_RAND_RESET_I(32);
    vlSelf->__Vtogcov__print_trace = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_imm_i__0__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__0__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__1__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__1__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__2__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__2__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__3__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__3__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__4__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__4__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__5__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__5__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__6__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__6__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__7__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__7__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_shamt__8__Vfuncout = VL_RAND_RESET_I(5);
    vlSelf->__Vfunc_imm_shamt__8__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_u_sh12__9__Vfuncout = VL_RAND_RESET_I(20);
    vlSelf->__Vfunc_imm_u_sh12__9__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_u_sh12__10__Vfuncout = VL_RAND_RESET_I(20);
    vlSelf->__Vfunc_imm_u_sh12__10__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__11__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__11__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_s__12__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_s__12__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_j__13__Vfuncout = VL_RAND_RESET_I(21);
    vlSelf->__Vfunc_imm_j__13__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_i__14__Vfuncout = VL_RAND_RESET_I(12);
    vlSelf->__Vfunc_imm_i__14__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__15__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__15__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__16__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__16__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__17__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__17__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__18__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__18__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__19__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__19__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_imm_b__20__Vfuncout = VL_RAND_RESET_I(13);
    vlSelf->__Vfunc_imm_b__20__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vdly__inst = VL_RAND_RESET_I(32);
    vlSelf->__Vdly__PC = VL_RAND_RESET_I(32);
    vlSelf->__Vdly__PC_prev = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v0 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvset__rf__v0 = 0;
    vlSelf->__Vdlyvval__rf__v1 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v2 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v3 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v4 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v5 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v6 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v7 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v8 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v9 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v10 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v11 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v12 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v13 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v14 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v15 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v16 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v17 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v18 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v19 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v20 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v21 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v22 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v23 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v24 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v25 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v26 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v27 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v28 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v29 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v30 = VL_RAND_RESET_I(32);
    vlSelf->__Vdlyvval__rf__v31 = VL_RAND_RESET_I(32);
    vlSelf->__Vdly__state = 0;
}
