// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop__Syms.h"
#include "Vtop__Syms.h"
#include "Vtop_vc_Queue__Pz3_PB4d_PC1.h"

VL_ATTR_COLD void Vtop_vc_Queue__Pz3_PB4d_PC1___configure_coverage(Vtop_vc_Queue__Pz3_PB4d_PC1* vlSelf, bool first) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vtop_vc_Queue__Pz3_PB4d_PC1___configure_coverage\n"); );
    // Body
    if (false && first) {}  // Prevent unused
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5209]), first, "../vc/queues.v", 394, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "clk", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5210]), first, "../vc/queues.v", 395, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "reset", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5211]), first, "../vc/queues.v", 397, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_val", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5212]), first, "../vc/queues.v", 398, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_rdy", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5213]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5214]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5215]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5216]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5217]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5218]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5219]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5220]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5221]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5222]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5223]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5224]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5225]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5226]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5227]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5228]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5229]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5230]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5231]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5232]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5233]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5234]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5235]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5236]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5237]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[24]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5238]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[25]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5239]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[26]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5240]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[27]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5241]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[28]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5242]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[29]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5243]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[30]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5244]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[31]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5245]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[32]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5246]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[33]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5247]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[34]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5248]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[35]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5249]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[36]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5250]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[37]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5251]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[38]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5252]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[39]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5253]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[40]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5254]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[41]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5255]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[42]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5256]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[43]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5257]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[44]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5258]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[45]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5259]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[46]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5260]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[47]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5261]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[48]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5262]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[49]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5263]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[50]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5264]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[51]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5265]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[52]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5266]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[53]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5267]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[54]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5268]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[55]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5269]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[56]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5270]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[57]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5271]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[58]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5272]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[59]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5273]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[60]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5274]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[61]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5275]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[62]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5276]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[63]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5277]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[64]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5278]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[65]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5279]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[66]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5280]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[67]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5281]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[68]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5282]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[69]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5283]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[70]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5284]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[71]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5285]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[72]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5286]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[73]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5287]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[74]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5288]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[75]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5289]), first, "../vc/queues.v", 399, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "enq_msg[76]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5290]), first, "../vc/queues.v", 401, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_val", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5291]), first, "../vc/queues.v", 402, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_rdy", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5292]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5293]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5294]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5295]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5296]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5297]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5298]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5299]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5300]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5301]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5302]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5303]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5304]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5305]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5306]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5307]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5308]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5309]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5310]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5311]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5312]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5313]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5314]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5315]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5316]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[24]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5317]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[25]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5318]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[26]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5319]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[27]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5320]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[28]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5321]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[29]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5322]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[30]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5323]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[31]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5324]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[32]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5325]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[33]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5326]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[34]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5327]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[35]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5328]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[36]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5329]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[37]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5330]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[38]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5331]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[39]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5332]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[40]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5333]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[41]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5334]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[42]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5335]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[43]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5336]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[44]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5337]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[45]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5338]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[46]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5339]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[47]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5340]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[48]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5341]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[49]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5342]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[50]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5343]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[51]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5344]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[52]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5345]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[53]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5346]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[54]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5347]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[55]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5348]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[56]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5349]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[57]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5350]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[58]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5351]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[59]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5352]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[60]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5353]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[61]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5354]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[62]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5355]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[63]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5356]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[64]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5357]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[65]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5358]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[66]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5359]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[67]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5360]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[68]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5361]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[69]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5362]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[70]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5363]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[71]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5364]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[72]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5365]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[73]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5366]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[74]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5367]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[75]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5368]), first, "../vc/queues.v", 403, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "deq_msg[76]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5369]), first, "../vc/queues.v", 405, 34, "", "v_toggle/vc_Queue__Pz3_PB4d_PC1", "num_free_entries[0]", "");
}
